#!/bin/sh /etc/rc.common
# Copyright (C) 2022 Ghiora Drori
# System init.d script for  Openwrt /etc/init.d/noipv6

# After rnd 99 is started    
START=100

# Before network 90 is stopped
STOP=89

start_service() {
	# The script will wait for an ipv4 address on the NOIP_INTERFACE in /etc/noipv6
	/etc/config/wait_for_ip4_address.sh  & 		
}

# Command to launch application on reboot

start() {        
        echo start
	# The script will wait for an ipv4 address on the NOIP_INTERFACE in /etc/noipv6
	/etc/config/wait_for_ip4_address.sh  & 		
}                 
 
stop_service() {          
        echo stop
        # commands to kill application 
        killall  noipv6
}

stop() {          
        echo stop
        # commands to kill application 
        killall  noipv6
}

